- name: Setup Docker and run Nginx
  hosts: launched
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Create web folder
      file:
        path: /usr/share/nginx/html
        state: directory
        mode: '0755'

    - name: Upload custom index.html
      copy:
        src: index.html
        dest: /usr/share/nginx/html/index.html

    - name: Run Nginx container
      command: >
        docker run -d --name mynginx -p 80:80
        -v /usr/share/nginx/html:/usr/share/nginx/html:ro nginx
      args:
        creates: /var/lib/docker/containers
